# Generated by Django 5.1.7 on 2025-03-31 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_de_semelle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de semelle')),
                ('matieres_premieres', models.JSONField(blank=True, null=True, verbose_name='Matières premières')),
                ('origine', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origine')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_creative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('pointure', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pointure')),
                ('code_bar', models.CharField(max_length=50, unique=True, verbose_name='Code-barres')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ProduitCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catalogue')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit')),
            ],
            options={
                'unique_together': {('produit', 'catalogue')},
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='produits',
            field=models.ManyToManyField(related_name='catalogues', through='products.ProduitCatalogue', to='products.produit', verbose_name='Produits'),
        ),
        migrations.CreateModel(
            name='ProduitCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit')),
            ],
            options={
                'unique_together': {('produit', 'categorie')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(related_name='produits', through='products.ProduitCategorie', to='products.categories', verbose_name='Catégories'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_promo', models.CharField(max_length=255, verbose_name='Type de promotion')),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Réduction')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='SousCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='products.categories', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
            },
        ),
    ]
