# Generated by Django 5.1.7 on 2025-03-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitcatalogue',
            options={'verbose_name': 'Produit - Catalogue', 'verbose_name_plural': 'Produits - Catalogues'},
        ),
        migrations.AlterModelOptions(
            name='produitcategorie',
            options={'verbose_name': 'Produit - Catégorie', 'verbose_name_plural': 'Produits - Catégories'},
        ),
    ]
