# Generated by Django 5.1.7 on 2025-04-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produitcatalogue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creative',
            options={'verbose_name': 'Creative', 'verbose_name_plural': 'Creatives'},
        ),
    ]
