# Generated by Django 5.1.7 on 2025-03-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_etat', models.CharField(max_length=255, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'État de commande',
                'verbose_name_plural': 'États de commande',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True, verbose_name='Date de commande')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de livraison')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Région')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client', verbose_name='Client')),
                ('etat_commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='commandes.etatcommande', verbose_name='État')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_promo', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de réduction')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_promo', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='products.article', verbose_name='Article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_de_reduction', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de réduction')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Remise',
                'verbose_name_plural': 'Remises',
            },
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif du retour')),
                ('date_retour', models.DateField(auto_now_add=True, verbose_name='Date du retour')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='clients.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'unique_together': {('client', 'produit')},
            },
        ),
    ]
